# Generated by Django 3.1 on 2022-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='elec',
            field=models.IntegerField(blank=True, null=True, verbose_name='برق مصرفی'),
        ),
        migrations.AddField(
            model_name='product',
            name='light',
            field=models.IntegerField(blank=True, null=True, verbose_name='میزان نور'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
