# Generated by Django 3.1 on 2022-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_auto_20220421_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lightcolor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='رنگ نور'),
        ),
    ]
