# Generated by Django 3.1 on 2022-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0009_auto_20220421_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
