# Generated by Django 3.1 on 2022-04-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0003_auto_20220411_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'دسته بندی اصلی', 'verbose_name_plural': 'دسته بندی های اصلی'},
        ),
    ]
