# Generated by Django 3.1 on 2022-04-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0005_auto_20220429_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='categories',
            field=models.CharField(max_length=150, null=True, verbose_name='دسته بندی اصلی'),
        ),
    ]
